local opt = vim.opt

opt.laststatus = 3
opt.showmode = false
opt.title = true
opt.expandtab = true
opt.backup = false
opt.writebackup = false
opt.cmdheight = 1
opt.completeopt = { "menuone", "noselect" }
opt.conceallevel = 0
opt.smartcase = true
opt.smartindent = true
opt.swapfile = false
opt.undofile = true
opt.updatetime = 50
opt.tabstop = 2
opt.shiftwidth = 2
opt.number = true
opt.relativenumber = true
opt.signcolumn = "yes"
opt.wrap = false
opt.numberwidth = 4
opt.hlsearch = true
opt.fileencoding = "utf-8"
opt.termguicolors = true
opt.cursorline = true
